version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always
    networks:
      - movies-network
    environment:
      - REDIS_PASSWORD=191688
    ports:
      - "6379:6379"
  db-container:
    image: postgres:latest
    restart: always
    networks:
      - movies-network
    environment:
      POSTGRES_USER: dbmsuser
      POSTGRES_PASSWORD: 191688
      POSTGRES_DB: movieservicebd
    volumes:
      - /home/wupdp/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  dbms-service:
    build: ./dbms-service
    image: dbms-service:latest
    restart: always
    networks:
      - movies-network
    depends_on:
      - db-container
      - redis
    environment:
      DATABASE_URL: db-container:5432
    volumes:
      - /home/wupdp/logs/dbms:/app/logs
    ports:
      - "8080:8080"

  api-service:
    build: ./api-service
    image: api-service:latest
    restart: always
    networks:
      - movies-network
    volumes:
      - /home/wupdp/logs/api:/app/logs
    ports:
      - "8081:8081"
  db-controller:
    build: ./db-controller
    image: db-controller
    restart: always
    environment:
      DBMS_URL: http://dbms-service:8080/
      API_URL: http://api-service:8081/
    networks:
      - movies-network
    ports:
      - "8088:8088"
    volumes:
      - /home/wupdp/logs/controller:/app/logs
  prometheus:
    image: prom/prometheus
    restart: always
    networks:
      - movies-network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - movies-network
networks:
  movies-network:
    driver: bridge
