###test movie
GET http://localhost:8080/movies



###
GET http://localhost:8080/movies/byCountry/TEST

###
GET http://localhost:8080/movies/byGenre/TEST

###
GET http://localhost:8080/movies/byPerson/TEST

###
GET http://localhost:8080/movies/byTitle/Avengers

###
GET http://localhost:8080/movies/2

###
DELETE http://localhost:8080/movies/1

###
GET http://localhost:8080/persons

###
POST http://localhost:8080/persons
Content-Type: application/json

{
  "id": 0,
  "name": "",
  "description": ""
}

###
GET http://localhost:8080/persons/{{id}}

###
DELETE http://localhost:8080/persons/{{id}}

###
GET http://localhost:8080/countries

###
POST http://localhost:8080/countries
Content-Type: application/json

{
  "id": 0,
  "name": "TEST"
}

###
GET http://localhost:8080/countries/{{id}}

###
DELETE http://localhost:8080/countries/{{id}}

###
GET http://localhost:8080/genres

###
POST http://localhost:8080/genres
Content-Type: application/json

{
  "id": 0,
  "name": "TEST2"
}

###
GET http://localhost:8080/genres/2

###
DELETE http://localhost:8080/genres/2