apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: {{ .Values.apiService.image }}
          volumeMounts:
            - mountPath: /app/logs
              name: api-logs
          ports:
            - containerPort: 8081
      volumes:
        - name: api-logs
          hostPath:
            path: {{ .Values.apiService.volumeMount }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: api-service
